POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NjY4NjM0NmU1NGIxMjUzNWY5NTk0Y2IiLCJpYXQiOjE3MTgxMTczMTIsImV4cCI6MTcxODEyMDkxMn0.aiHMfOvfbQLjDBWnRS8NueVbLEzCFopoR-WrHZ6bcSA

{
  "url": "https://overreacted.io/things-i-dont-know-as-of-2018/",
  "title": "Things I Don't Know as of 2018",
  "author": "Dan Abramov",
  "likes": 0
}